### ISSUE TITLE
Question. How do I know which Users are enrolled in which campaigns?

### ISSUE THREAD

**Issue by davidflores2** [honeybadger-io/heya#132]
I'm using the gem and am having a hard time trying to find out which user is a member of which campaign. Is there a way of knowing?

**Comment by joshuap** [comment]
There's currently no way to do this without querying directly. You can do something like this, I think:

```ruby
Heya::Campaign.where(user: contact).all
```

**Comment by feliperaul** [comment]
`Heya::Campaign` is currently undefined for me. 

However, you can do it like this:

```ruby
Heya::CampaignMembership.where(user: User.last)
```

The campaigns will be indicated in the `campaign_id` column. It's a global ID string. If you want to instanciate them:
```ruby
# Heya already includes the GlobalID gem
Heya::CampaignMembership.where(user: user).map {|membership| GlobalID::Locator.locate(membership.campaign_gid) }
```

Lastly, if you want all the users subscribed to a campaign (for instance, your `OnboardingCampaign`):

```ruby
User.where(id: Heya::CampaignMembership.where(campaign_gid: OnboardingCampaign.gid).select("user_id")).distinct
```
