### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by davidflores2** [honeybadger-io/heya#133]
I noticed that the migrations are tied to a User and that the initializer asks for which object will be used on the campaigns. In my case, the users will send campaigns to Contacts. It would be nice to be able to specify in the generator the resource that will be used so the migration is created correctly, something like `rails generate heya:install -r Contact`

**Comment by joshuap** [comment]
Hi @davidflores2, the column name in the migration is `user` (which shouldn't change), but the association is polymorphic, so you can use whatever model you want. You can configure the user model in the initializer:

https://github.com/honeybadger-io/heya#configuration
