### ISSUE TITLE
Can we delegate the `layout` so we can re-use already existing layouts?

### ISSUE THREAD

**Issue by panbanda** [honeybadger-io/heya#142]
I would assume adding something here like `layout "mailer"` would be a nice feature to have.  This extends from Base so not sure the best route to go about specifying the layout.

```
class ApplicationCampaign < Heya::Campaigns::Base
  default queue: "custom", from: "support@email.com"
end
```

**Comment by joshuap** [comment]
@panbanda yeah, I think that would be a nice option. I *believe* all extra options get passed through to `step.params` automatically, so we'd just need to allow overriding the layout with `step.params.fetch("layout", "heya/campaign_mailer")` in the mailer:

https://github.com/honeybadger-io/heya/blob/master/app/mailers/heya/campaign_mailer.rb

I can't get to this right away, but you're welcome to submit a PR if you want to take a shot at it!
