### ISSUE TITLE
New install error: relation "heya_steps" does not exist 

### ISSUE THREAD

**Issue by acallaghan** [honeybadger-io/heya#145]
Hey there, I've been integrating Heya with our app, and came across this issue. I have added the gem and run the installation commands and migration. I then setup my first campaign.

However, when I run the campaign scheduling rake task, I get this error:

```
$ rails heya:scheduler 
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "heya_steps" does not exist
LINE 1: ...M "public"."heya_campaign_memberships" INNER JOIN "heya_step...
                                                             ^
Caused by:
PG::UndefinedTable: ERROR:  relation "heya_steps" does not exist
LINE 1: ...M "public"."heya_campaign_memberships" INNER JOIN "heya_step...
                                                             ^

Tasks: TOP => heya:scheduler
(See full trace by running task with --trace)
```

A `--trace` led me to the lines:

```
lib/heya/campaigns/scheduler.rb:21:in `run'
lib/tasks/heya_tasks.rake:6:in `block (2 levels) in <main>'
```

It looks like these files are referring to a table called `heya_steps`, and referenced in a few places like:

```ruby
scope :with_steps, -> {
  joins(
    %(INNER JOIN "heya_steps" ON "heya_steps".gid = "heya_campaign_memberships".step_gid)
  )
}
```

This table isn't in the generator for the installation migration, so not sure where this should come from? Any ideas would be welcome!

I'm using Rails 6.1, Ruby 3.0.1 and postrges 13.3 

Thanks in advance,
Andy

**Comment by kimili** [comment]
Hi @joshuap! Just a heads up on this old issue. It looks like if you try to set up campaigns in subdirectories of the `app/campaigns` folder, you'll hit this issue. Not sure if that's something worth investigating, or at least make a note of in the docs.

**Comment by joshuap** [comment]
> Hi @joshuap! Just a heads up on this old issue. It looks like if you try to set up campaigns in subdirectories of the `app/campaigns` folder, you'll hit this issue. Not sure if that's something worth investigating, or at least make a note of in the docs.

@kimili thanks! I created a new issue to remind myself to investigate this when I have the time. 😁 

https://github.com/honeybadger-io/heya/issues/264
