### ISSUE TITLE
Url helpers returning NameError

### ISSUE THREAD

**Issue by feliperaul** [honeybadger-io/heya#154]
First of all, great gem! Really enjoyed exploring the code.

I'm facing NameErrors on every single url helper I try to use inside a template.

For instance, a simple `<% link_to "Home", root_url %>` returns  `undefined local variable or method `root_url' for #<ActionView::Base:0x0000000005f668>`.

Maybe `Heya::Campaigns::Base` should include `Rails.application.routes.url_helpers` ?

Thanks!

**Comment by joshuap** [comment]
Thanks, glad you like it!

I agree, it would be ideal if `Rails.application.routes.url_helpers` is automatically included inside of Heya's templates. For some reason I thought they were—are they included `ActionMailer::Base` (which we subclass [here](https://github.com/honeybadger-io/heya/blob/master/app/mailers/heya/application_mailer.rb)) by default?

**Comment by feliperaul** [comment]
@joshuap Joshua, I can reproduce the exception even in a fresh Rails app with heya (see link below), so I can confirm this is indeed a bug.

I can also confirm a simple `include Rails.application.routes.url_helpers` in `Heya::CampaignMailer` solves it.

I couldn't, however, dig deep enough to understand why this is going on. If you want to check out how weird this is, take a look at https://github.com/feliperaul/temp_heya and go to http://localhost:3000/rails/mailers

You'll see two previews. One of them uses Heya, the other one is a regular rails mailer. Heya's will raise, the other will not. 

The funny part is that I set the rails mailer to render the exact same template as Heya is using (by passing `template_path` and `template_name` to the `#mail` method), and the exception doesn't occur; but for some reason that escapes me the Heya mailer (which inherits from ActionMailer::Base) will raise on`root_url`. 

I hate fixing code without fully understanding what is goin on, but I don't have time to dig deeper right now; since this bug is very inconvenient, I sent #158 as a PR, but I wouldn't mind if you told me what is going on here 🤣

**Comment by joshuap** [comment]
Fix released in 0.7.0. Thanks for the help!
