### ISSUE TITLE
Option to set a List-Unsubscribe Header in the email 

### ISSUE THREAD

**Issue by leemcalilly** [honeybadger-io/heya#160]
Could work similar to how other options like subject or from work.

**Comment by joshuap** [comment]
I like the idea of adding a `:headers` option to Heya campaigns and using it to [set the headers in the mailer](https://api.rubyonrails.org/v7.0.2.2/classes/ActionMailer/Base.html#method-i-headers).

**Comment by joshuap** [comment]
Closed by #202
