### ISSUE TITLE
Defining email subject in locale files throws exception on Rails 7 startup

### ISSUE THREAD

**Issue by kimili** [honeybadger-io/heya#211]
Hi,

I'm trying to implement Heya in my app running Rails 7.0.6. In setting up campaigns, I've opted to put my email subjects in translation files, as suggested in the docs. However, when I do this, the validation for a subject throws an error during the Rails boot up:

```shell
/Users/michael/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/heya-c6dee57eb6e4/lib/heya/campaigns/actions/email.rb:12:in `validate_step': "subject" is required (ArgumentError)

            raise ArgumentError.new(%("subject" is required))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Putting a `debugger` in `campaigns/actions/email.rb`, I found that at the time that validation is happening, Rails hasn't yet loaded the locale files. As a result this, on line 11 of that file, returns `false`:

```ruby
I18n.exists?("#{step.campaign_name.underscore}.#{step.name.underscore}.subject")
```

I know my locales do eventually get loaded, because if I comment out the steps of my campaigns and open up a Rails console, that same line above returns `true` at that point.

Of course I can define the `subject`s in line with my steps, but I'd rather keep everything in locale files.

**Comment by joshuap** [comment]
@kimili thanks for the detail! I'll take a look.

**Comment by joshuap** [comment]
@kimili can you take a look at #216 and let me know what you think?

**Comment by kimili** [comment]
@joshuap - Sorry for the delay, just got a chance to test this out locally with Rails 7.1. The fix looks good on my end!
