### ISSUE TITLE
Does not seem to support MySQL

### ISSUE THREAD

**Issue by khash** [honeybadger-io/heya#220]
I haven't been able to find any references to the DB backend supported by this and given that Rails ActiveRecord decouples apps from the differences of the underlying DB, it is reasonable to assume the gem supports at least PG and MySQL. But I can't see how it would support MySQL when it constructs queries using the `VALUES` statement without the `ROW` (which is required for MySQL - https://github.com/honeybadger-io/heya/blob/02ef0c639ba37089f6989ed316ec43941ddb615e/lib/heya/active_record_extension.rb#L13)

As it is, a simple campaign will fail to run on MySQL when `Heya::Campaigns::Scheduler.new.run` is called with a SQL error like this:

```
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('gid://heya/Heya::Campaigns::Step/OnboardingCampaign%2Fwelcome', 172800), ('gid' at line 1>
```

I think at the very least, the lack of support for MySQL should be stated in the docs

**Comment by halfbyte** [comment]
@khash We'll have a look at this. I agree with your assessment that the minimal step would be to document the dependency on Postgresql, but looking at the syntax differences, this should be doable, I hope.

**Comment by joshuap** [comment]
Yeah, this really is built for Postgres, and I don’t really want to personally support MySQL, although I’d consider a PR if someone does it. We should mention PG-only in the readme though. 👍
