### ISSUE TITLE
Option for a strong copy-left license like the AGPL instead of PPL?

### ISSUE THREAD

**Issue by wwahammy** [honeybadger-io/heya#84]
Hey all, I work on the Houdini Project, a nonprofit online fundraising suite built on Ruby on Rails. I was super excited finding a Gem that could use for nonprofit email campaigns like Heya. Unfortunately, your license prevents us from doing so. We use the Affero GPL license for our work which requires that anyone making an instance of the Houdini Project available via a network provide the corresponding code under the AGPL or a compatible license. The AGPL doesn't have restrictions for commercial use, like all free software licenses recognized by the Free Software Foundation or open source licenses recognized by the Open Source Initiative, so we can't use Heya. (I'd be happy to get you in touch with the President of the OSI if you'd like to discuss why the PPL isn't an open source license)

I don't get the impression that you intended for Heya to not be used in software like ours so what I propose is a compromise: dual licensing under the AGPL and PPL. Any software can be licensed under multiple licenses by its copyright holders and the user can choose which license they would like to use it under. The AGPL, while fully open source and free, is not popular among most large companies, like Google, Facebook, Amazon, etc. It's primarily used by smaller companies and nonprofits for software like Mastodon and CiviCRM. The reason is that big companies don't like that it requires you to open source all of the software its combined with. For companies like that, they don't want to reveal any of their internal software. On the other hand, nonprofits and small companies like mine (2 people) who primarily work with nonprofits and committed to open source are willing to do so.

Dual licensing Heya allows a user to make a choice: either open source the Rails software you're adding Heya into or don't open source and choose to accept the restrictions of the PPL. The largest companies will, by and large, pick the PPL every day. Some smaller companies will too. Nonprofits and companies like mine who provide fundraising services for nonprofits are going to be more willing to use

Is this something you'd be interested in? Relicensing isn't much of an effort as long as you don't have many outside contributors yet and I'd be happy to help.

**Comment by joshuap** [comment]
@wwahammy thank you for the detailed writeup! I'm just checking in--I'm still thinking about this one. I'm not immediately inclined to provide a dual license with the AGPL, since there are commercial companies who's code is open source but should still pay.

**Comment by joshuap** [comment]
After thinking about this, I'm not interested in offering an AGPL/copy-left license at this time. I may change the license in the future, but I'm not quite there yet. Thanks again for the info.
